[package]
name = "rays"
version = "0.1.0"
authors = ["4dsolutions <kirby.urner@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.3.2"